trigger:

- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: hts2-onec-docker-dev.jfrog.io/$(imageName)
    containerRegistry: 'Jfrog Docker registry'
    command: build
    Dockerfile: app/Dockerfile
    tags: 'latest'
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'hts2'
    targetRepo: 'onec-docker-dev'
    imageName: 'hts2-onec-docker-dev.jfrog.io/pipelines-javascript-docker:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'hts2'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'