trigger:
- master
pool:
  vmImage: 'Ubuntu-20.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: sandeepmkp.jfrog.io/docker-local/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'ujwal-artifactory'
    imageName: 'sandeepmkp.jfrog.io/docker-local/$(imageName):$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'ujwal-artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'