trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: sandeepmkp.jfrog.io/docker-local/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'tata'
    targetRepo: 'docker-local'
    imageName: 'sandeepmkp.jfrog.io/$(imageName):$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'tata'
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)







