trigger:

- master
pool: 'podman'

variables:
  imageName: 'pipelines-javascript-docker'

steps:

- task: Docker@2
  inputs:
    repository: 'a8d1-35-241-242-81.eu.ngrok.io/test-docker/tde/ado/$(imageName)'
    command: 'build'
    Dockerfile: 'app/Dockerfile'
    tags: 'latest'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'podman'
    command: 'jf rt pp a8d1-35-241-242-81.eu.ngrok.io/test-docker/tde/ado/$(imageName):latest test-docker --build-name=Jfrogartifactory-testpipeline --build-number=20230316.9'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'podman'
    command: 'jf rt bp Jfrogartifactory-testpipeline 20230316.9'
